##
## EPITECH PROJECT, 2019
## Makefile
## File description:
## Makefile compilling all binaries
##

all:
	make -C ./solver
	make -C ./generator

.PHONY: fclean
fclean:
	make -C ./solver fclean
	make -C ./generator fclean

.PHONY: clean
clean:
	make -C ./solver clean
	make -C ./generator clean
